version: '3'
services:
  app: 
    image: node
    user: node:node
    working_dir: /app
    container_name: app-certifications
    depends_on:
      - database
    ports: 
      - '5001:3000'
    networks:
      - default
      - app-courses_default
    volumes:
      - ./:/app
    command: 'npm run start:dev'

  database:
    image: postgres
    container_name: postgres_db_certifications
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRESS_DB: db_certifications
    ports:
      - '5434:5432'
    volumes:
      - db_certifications:/var/lib/postgresql/data
    networks:
      - default

volumes:
  db_certifications:
    driver: local
networks:
  default:
    driver: bridge
  app-courses_default:
    external: true